/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadgrupo9.vistas;

import java.awt.HeadlessException;
import java.time.LocalDate;
import java.time.ZoneId;

import javax.swing.JOptionPane;
import universidadgrupo9.accesoADatos.AlumnoData;
import universidadgrupo9.entidades.Alumno;

/**
 *
 * @author jfaja
 */
public class AlumnosVista extends javax.swing.JInternalFrame {

    /**
     * Creates new form AlumnosVista
     */
    public AlumnosVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize
     * the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTFDni = new javax.swing.JTextField();
        jTFApellido = new javax.swing.JTextField();
        jTFNombre = new javax.swing.JTextField();
        jBBuscarAlumnoXDNI = new javax.swing.JButton();
        jRadioBEstado = new javax.swing.JRadioButton();
        jBNuevo = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jBBuscarxApellido = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTFidalumno = new javax.swing.JTextField();
        jBBuscarXid = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Gestion de Alumnos");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Alumno");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Documento:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Apellido");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Estado");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Fecha de Nacimiento");

        jBBuscarAlumnoXDNI.setText("Buscar");
        jBBuscarAlumnoXDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarAlumnoXDNIActionPerformed(evt);
            }
        });

        jBNuevo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jBNuevo.setText("Nuevo");

        jBEliminar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBGuardar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBSalir.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jBSalir.setText("Salir");

        jBBuscarxApellido.setText("Buscar");
        jBBuscarxApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarxApellidoActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jBBuscarXid.setText("Buscar");
        jBBuscarXid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarXidActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setText("Legajo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioBEstado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTFidalumno, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTFNombre)
                                    .addComponent(jTFDni)
                                    .addComponent(jTFApellido))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBBuscarAlumnoXDNI)
                                    .addComponent(jBBuscarxApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2)
                                    .addComponent(jBBuscarXid)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBEliminar)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBBuscarAlumnoXDNI)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBBuscarxApellido)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jRadioBEstado))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFidalumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBBuscarXid)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBNuevo)
                    .addComponent(jBEliminar)
                    .addComponent(jBGuardar)
                    .addComponent(jBSalir))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarAlumnoXDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarAlumnoXDNIActionPerformed

        // Obtén el DNI ingresado en el campo de texto
        try {
            int dni = Integer.parseInt(jTFDni.getText());

            // Crea una instancia de AlumnoData 
            AlumnoData alumnoData = new AlumnoData();

            // Llama al método buscarAlumnoPorDNI de AlumnoData para obtener los datos del alumno
            Alumno alumno = alumnoData.buscaAlumnoPorDni(dni);

            if (alumno != null) {
                // Si se encontró al alumno, muestra sus datos en los campos del formulario
                jTFDni.setText(Integer.toString(alumno.getDni()));
                jTFidalumno.setText(Integer.toString(alumno.getId()));
                jTFApellido.setText(alumno.getApellido());
                jTFNombre.setText(alumno.getNombre());
                jRadioBEstado.setSelected(alumno.isEstado());

                // Convierte la fecha de nacimiento a un objeto java.util.Date
                java.util.Date fechaNacimiento = java.sql.Date.valueOf(alumno.getFechaN());
                jDateChooser1.setDate(fechaNacimiento);

            } else {                // Si no se encontró al alumno
                JOptionPane.showMessageDialog(this, "Alumno no encontrado");
            }
        } catch (NumberFormatException e) {//si no hay numeros
            JOptionPane.showMessageDialog(this, "Error: Ingresa un número válido en el campo DNI  " + e.getMessage());
        } catch (HeadlessException e) {//captura lo que sea que este mal
            JOptionPane.showMessageDialog(this, "Error: Ocurrió un problema al buscar al alumno" + e.getMessage());
        }
    }//GEN-LAST:event_jBBuscarAlumnoXDNIActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed

        try {
            // Verifica si los campos de texto están vacíos
            if (jTFDni.getText().isEmpty() || jTFApellido.getText().isEmpty() || jTFNombre.getText().isEmpty() || jDateChooser1.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Error: Uno o más campos están vacíos");
                return;
            }

            // Obtén los datos de la clase vista 
            int dni = Integer.parseInt(jTFDni.getText());
            String apellido = jTFApellido.getText();
            String nombre = jTFNombre.getText();
            java.util.Date fechaNacimientoUtil = (java.util.Date) jDateChooser1.getDate();
            LocalDate fechaNacimiento = fechaNacimientoUtil.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            boolean estado = jRadioBEstado.isSelected(); // Si el botón de radio está seleccionado, estado será true

            // Crea un objeto Alumno con los datos del formulario
            Alumno nuevoAlumno = new Alumno(dni, apellido, nombre, fechaNacimiento, estado);

            AlumnoData alumnoData = new AlumnoData(); // Crea una instancia de AlumnoData
            alumnoData.guardarAlumno(nuevoAlumno); // envia el alumno en la base de datos para ser guardado

            // Limpia los campos del formulario después de guardar
            jTFDni.setText("");
            jTFApellido.setText("");
            jTFNombre.setText("");
            jRadioBEstado.setSelected(false);
            jDateChooser1.setDate(null);
        } catch (NumberFormatException ex) { //captura si se ingresa una letra          
            JOptionPane.showMessageDialog(this, "Hay algún error en los campos numéricos -" + ex.getMessage());
        } catch (HeadlessException e) { //captura lo que sea que esté mal
            JOptionPane.showMessageDialog(this, "Error: Ocurrió un problema al buscar al alumno" + e.getMessage());

        }

    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed

        try {

            int dni = Integer.parseInt(jTFDni.getText());

            if (!jTFDni.getText().matches("\\d+")) {
                throw new Exception("El campo DNI debe ser un número entero");
            }

            AlumnoData alumnoData = new AlumnoData();
            alumnoData.eliminarAlumno(dni);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El campo DNI está vacío" + e);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error imprevisto!!!" + e.getMessage());
        }

        // Limpia los campos del formulario después de eliminar
        jTFDni.setText("");
        jTFidalumno.setText("");
        jTFApellido.setText("");
        jTFNombre.setText("");
        jRadioBEstado.setSelected(false);
        jDateChooser1.setDate(null);


    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // Obtén el nombre ingresado en el campo de texto
        String nombre = jTFNombre.getText();

        // Crea una instancia de AlumnoData 
        AlumnoData alumnoData = new AlumnoData();

        // Llama al método buscarAlumnoPorNombre de AlumnoData para obtener los datos del alumno
        Alumno alumno = alumnoData.buscarAlumno(nombre);

        if (alumno != null) {

            // Si se encontró al alumno, muestra sus datos en los campos del formulario
            jTFDni.setText(Integer.toString(alumno.getDni()));
            jTFidalumno.setText(Integer.toString(alumno.getId()));
            jTFApellido.setText(alumno.getApellido());
            jTFNombre.setText(alumno.getNombre());
            jRadioBEstado.setSelected(alumno.isEstado());

            // Convierte la fecha de nacimiento a un objeto java.util.Date
            java.util.Date fechaNacimiento = java.sql.Date.valueOf(alumno.getFechaN());
            jDateChooser1.setDate(fechaNacimiento);

        } else {                // Si no se encontró al alumno
            JOptionPane.showMessageDialog(this, "Alumno no encontrado");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBBuscarxApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarxApellidoActionPerformed
        // Obtén el nombre ingresado en el campo de texto
        String apellido = jTFApellido.getText();

        // Crea una instancia de AlumnoData 
        AlumnoData alumnoData = new AlumnoData();

        // Llama al método buscarAlumnoPorNombre de AlumnoData para obtener los datos del alumno
        Alumno alumno = alumnoData.buscarApellido(apellido);

        if (alumno != null) {

            // Si se encontró al alumno, muestra sus datos en los campos del formulario             
            jTFDni.setText(Integer.toString(alumno.getDni()));
            jTFidalumno.setText(Integer.toString(alumno.getId()));
//            jTFApellido.setText(alumno.getApellido());
            jTFNombre.setText(alumno.getNombre());
            jRadioBEstado.setSelected(alumno.isEstado());

            // Convierte la fecha de nacimiento a un objeto java.util.Date
            java.util.Date fechaNacimiento = java.sql.Date.valueOf(alumno.getFechaN());
            jDateChooser1.setDate(fechaNacimiento);

        } else {                // Si no se encontró al alumno
            JOptionPane.showMessageDialog(this, "Alumno no encontrado");
        }

    }//GEN-LAST:event_jBBuscarxApellidoActionPerformed

    private void jBBuscarXidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarXidActionPerformed
        try {
            int id = Integer.parseInt(jTFidalumno.getText());
                
            // Crea una instancia de AlumnoData 
            AlumnoData alumnoData = new AlumnoData();

            // Llama al método buscarAlumnoPorDNI de AlumnoData para obtener los datos del alumno
            Alumno alumno = alumnoData.buscarXidAlumno(id);

            if (alumno != null) {
                // Si se encontró al alumno, muestra sus datos en los campos del formulario
//                jTFidalumno.setText(Integer.toString(alumno.getId()));
                jTFDni.setText(Integer.toString(alumno.getDni()));
                jTFApellido.setText(alumno.getApellido());
                jTFNombre.setText(alumno.getNombre());
                jRadioBEstado.setSelected(alumno.isEstado());
                // Convierte la fecha de nacimiento a un objeto java.util.Date
                java.util.Date fechaNacimiento = java.sql.Date.valueOf(alumno.getFechaN());
                jDateChooser1.setDate(fechaNacimiento);

            } else {                // Si no se encontró al alumno
                JOptionPane.showMessageDialog(this, "Alumno no encontrado");
            }
        } catch (NumberFormatException e) {//si no hay numeros
            JOptionPane.showMessageDialog(this, "Error: Ingresa un número válido en el campo DNI  " + e.getMessage());
        } catch (HeadlessException e) {//captura lo que sea que este mal
            JOptionPane.showMessageDialog(this, "Error: Ocurrió un problema al buscar al alumno" + e.getMessage());
        }
        
    }//GEN-LAST:event_jBBuscarXidActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscarAlumnoXDNI;
    private javax.swing.JButton jBBuscarXid;
    private javax.swing.JButton jBBuscarxApellido;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioBEstado;
    private javax.swing.JTextField jTFApellido;
    private javax.swing.JTextField jTFDni;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFidalumno;
    // End of variables declaration//GEN-END:variables
}
